/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ColorMode = IDL.Variant({ 'BW' : IDL.Null, 'Color' : IDL.Null });
export const PageSize = IDL.Variant({ 'A3' : IDL.Null, 'A4' : IDL.Null });
export const PrintSide = IDL.Variant({
  'Double' : IDL.Null,
  'Single' : IDL.Null,
});
export const PricingRule = IDL.Record({
  'colorMode' : ColorMode,
  'ruleId' : IDL.Text,
  'pageSize' : PageSize,
  'pricePerPage' : IDL.Nat,
  'printSide' : PrintSide,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PrintJobStatus = IDL.Variant({
  'uploaded' : IDL.Null,
  'readyToPrint' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PrintJob = IDL.Record({
  'status' : PrintJobStatus,
  'colorMode' : ColorMode,
  'copiesCount' : IDL.Nat,
  'userId' : IDL.Text,
  'pagesPerCopyCount' : IDL.Nat,
  'pagesCount' : IDL.Nat,
  'jobId' : IDL.Text,
  'fileBlob' : ExternalBlob,
  'fileName' : IDL.Text,
  'paperSize' : PageSize,
  'fileType' : IDL.Opt(IDL.Text),
  'sidesCount' : IDL.Nat,
  'colorPagesCount' : IDL.Nat,
  'price' : IDL.Nat,
  'printerId' : IDL.Text,
  'onlyBW' : IDL.Bool,
});
export const PrinterStatus = IDL.Variant({
  'Working' : IDL.Null,
  'OutOfPaper' : IDL.Null,
  'Offline' : IDL.Null,
});
export const Printer = IDL.Record({
  'status' : PrinterStatus,
  'queueCount' : IDL.Nat,
  'printerId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'student' : IDL.Null,
});
export const User = IDL.Record({
  'studentId' : IDL.Text,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : UserRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDefaultPricingRules' : IDL.Func([], [], []),
  'addPricingRule' : IDL.Func([PricingRule], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'calculatePrice' : IDL.Func([PrintJob], [IDL.Nat], []),
  'createPrintJob' : IDL.Func([IDL.Text, PrintJob], [], []),
  'createPrinter' : IDL.Func([Printer], [], []),
  'createUser' : IDL.Func([IDL.Text, User], [], []),
  'deletePricingRule' : IDL.Func([IDL.Text], [], []),
  'deletePrinter' : IDL.Func([IDL.Text], [], []),
  'getAllPricingRules' : IDL.Func([], [IDL.Vec(PricingRule)], ['query']),
  'getAllPrintJobs' : IDL.Func([], [IDL.Vec(PrintJob)], ['query']),
  'getAllPrinters' : IDL.Func([], [IDL.Vec(Printer)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getPricingRuleById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PricingRule)],
      ['query'],
    ),
  'getPrintJob' : IDL.Func([IDL.Text], [IDL.Opt(PrintJob)], ['query']),
  'getPrinter' : IDL.Func([IDL.Text], [IDL.Opt(Printer)], ['query']),
  'getTotalPrintJobs' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalRevenue' : IDL.Func([], [IDL.Nat], ['query']),
  'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePricingRule' : IDL.Func([IDL.Text, PricingRule], [], []),
  'updatePrinterStatus' : IDL.Func([IDL.Text, PrinterStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ColorMode = IDL.Variant({ 'BW' : IDL.Null, 'Color' : IDL.Null });
  const PageSize = IDL.Variant({ 'A3' : IDL.Null, 'A4' : IDL.Null });
  const PrintSide = IDL.Variant({ 'Double' : IDL.Null, 'Single' : IDL.Null });
  const PricingRule = IDL.Record({
    'colorMode' : ColorMode,
    'ruleId' : IDL.Text,
    'pageSize' : PageSize,
    'pricePerPage' : IDL.Nat,
    'printSide' : PrintSide,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PrintJobStatus = IDL.Variant({
    'uploaded' : IDL.Null,
    'readyToPrint' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PrintJob = IDL.Record({
    'status' : PrintJobStatus,
    'colorMode' : ColorMode,
    'copiesCount' : IDL.Nat,
    'userId' : IDL.Text,
    'pagesPerCopyCount' : IDL.Nat,
    'pagesCount' : IDL.Nat,
    'jobId' : IDL.Text,
    'fileBlob' : ExternalBlob,
    'fileName' : IDL.Text,
    'paperSize' : PageSize,
    'fileType' : IDL.Opt(IDL.Text),
    'sidesCount' : IDL.Nat,
    'colorPagesCount' : IDL.Nat,
    'price' : IDL.Nat,
    'printerId' : IDL.Text,
    'onlyBW' : IDL.Bool,
  });
  const PrinterStatus = IDL.Variant({
    'Working' : IDL.Null,
    'OutOfPaper' : IDL.Null,
    'Offline' : IDL.Null,
  });
  const Printer = IDL.Record({
    'status' : PrinterStatus,
    'queueCount' : IDL.Nat,
    'printerId' : IDL.Text,
  });
  const UserRole = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
  const User = IDL.Record({
    'studentId' : IDL.Text,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : UserRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDefaultPricingRules' : IDL.Func([], [], []),
    'addPricingRule' : IDL.Func([PricingRule], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'calculatePrice' : IDL.Func([PrintJob], [IDL.Nat], []),
    'createPrintJob' : IDL.Func([IDL.Text, PrintJob], [], []),
    'createPrinter' : IDL.Func([Printer], [], []),
    'createUser' : IDL.Func([IDL.Text, User], [], []),
    'deletePricingRule' : IDL.Func([IDL.Text], [], []),
    'deletePrinter' : IDL.Func([IDL.Text], [], []),
    'getAllPricingRules' : IDL.Func([], [IDL.Vec(PricingRule)], ['query']),
    'getAllPrintJobs' : IDL.Func([], [IDL.Vec(PrintJob)], ['query']),
    'getAllPrinters' : IDL.Func([], [IDL.Vec(Printer)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getPricingRuleById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PricingRule)],
        ['query'],
      ),
    'getPrintJob' : IDL.Func([IDL.Text], [IDL.Opt(PrintJob)], ['query']),
    'getPrinter' : IDL.Func([IDL.Text], [IDL.Opt(Printer)], ['query']),
    'getTotalPrintJobs' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalRevenue' : IDL.Func([], [IDL.Nat], ['query']),
    'getUser' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePricingRule' : IDL.Func([IDL.Text, PricingRule], [], []),
    'updatePrinterStatus' : IDL.Func([IDL.Text, PrinterStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };