/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ColorMode = { 'BW' : null } |
  { 'Color' : null };
export type ExternalBlob = Uint8Array;
export type PageSize = { 'A3' : null } |
  { 'A4' : null };
export interface PricingRule {
  'colorMode' : ColorMode,
  'ruleId' : string,
  'pageSize' : PageSize,
  'pricePerPage' : bigint,
  'printSide' : PrintSide,
}
export interface PrintJob {
  'status' : PrintJobStatus,
  'colorMode' : ColorMode,
  'copiesCount' : bigint,
  'userId' : string,
  'pagesPerCopyCount' : bigint,
  'pagesCount' : bigint,
  'jobId' : string,
  'fileBlob' : ExternalBlob,
  'fileName' : string,
  'paperSize' : PageSize,
  'fileType' : [] | [string],
  'sidesCount' : bigint,
  'colorPagesCount' : bigint,
  'price' : bigint,
  'printerId' : string,
  'onlyBW' : boolean,
}
export type PrintJobStatus = { 'uploaded' : null } |
  { 'readyToPrint' : null };
export type PrintSide = { 'Double' : null } |
  { 'Single' : null };
export interface Printer {
  'status' : PrinterStatus,
  'queueCount' : bigint,
  'printerId' : string,
}
export type PrinterStatus = { 'Working' : null } |
  { 'OutOfPaper' : null } |
  { 'Offline' : null };
export interface User {
  'studentId' : string,
  'userId' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : UserRole,
  'email' : string,
  'phone' : string,
  'department' : string,
}
export interface UserProfile {
  'studentId' : string,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'phone' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'student' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDefaultPricingRules' : ActorMethod<[], undefined>,
  'addPricingRule' : ActorMethod<[PricingRule], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'calculatePrice' : ActorMethod<[PrintJob], bigint>,
  'createPrintJob' : ActorMethod<[string, PrintJob], undefined>,
  'createPrinter' : ActorMethod<[Printer], undefined>,
  'createUser' : ActorMethod<[string, User], undefined>,
  'deletePricingRule' : ActorMethod<[string], undefined>,
  'deletePrinter' : ActorMethod<[string], undefined>,
  'getAllPricingRules' : ActorMethod<[], Array<PricingRule>>,
  'getAllPrintJobs' : ActorMethod<[], Array<PrintJob>>,
  'getAllPrinters' : ActorMethod<[], Array<Printer>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getPricingRuleById' : ActorMethod<[string], [] | [PricingRule]>,
  'getPrintJob' : ActorMethod<[string], [] | [PrintJob]>,
  'getPrinter' : ActorMethod<[string], [] | [Printer]>,
  'getTotalPrintJobs' : ActorMethod<[], bigint>,
  'getTotalRevenue' : ActorMethod<[], bigint>,
  'getUser' : ActorMethod<[string], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePricingRule' : ActorMethod<[string, PricingRule], undefined>,
  'updatePrinterStatus' : ActorMethod<[string, PrinterStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];