/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PricingRule {
    colorMode: ColorMode;
    ruleId: string;
    pageSize: PageSize;
    pricePerPage: bigint;
    printSide: PrintSide;
}
export interface UserProfile {
    studentId: string;
    name: string;
    role: UserRole;
    email: string;
    phone: string;
    department: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface User {
    studentId: string;
    userId: string;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
    phone: string;
    department: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PrintJob {
    status: PrintJobStatus;
    colorMode: ColorMode;
    copiesCount: bigint;
    userId: string;
    pagesPerCopyCount: bigint;
    pagesCount: bigint;
    jobId: string;
    fileBlob: ExternalBlob;
    fileName: string;
    paperSize: PageSize;
    fileType?: string;
    sidesCount: bigint;
    colorPagesCount: bigint;
    price: bigint;
    printerId: string;
    onlyBW: boolean;
}
export interface Printer {
    status: PrinterStatus;
    queueCount: bigint;
    printerId: string;
}
export enum ColorMode {
    BW = "BW",
    Color = "Color"
}
export enum PageSize {
    A3 = "A3",
    A4 = "A4"
}
export enum PrintJobStatus {
    uploaded = "uploaded",
    readyToPrint = "readyToPrint"
}
export enum PrintSide {
    Double = "Double",
    Single = "Single"
}
export enum PrinterStatus {
    Working = "Working",
    OutOfPaper = "OutOfPaper",
    Offline = "Offline"
}
export enum UserRole {
    admin = "admin",
    student = "student"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDefaultPricingRules(): Promise<void>;
    addPricingRule(rule: PricingRule): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    calculatePrice(printJob: PrintJob): Promise<bigint>;
    createPrintJob(jobId: string, printJob: PrintJob): Promise<void>;
    createPrinter(printer: Printer): Promise<void>;
    createUser(userId: string, user: User): Promise<void>;
    deletePricingRule(ruleId: string): Promise<void>;
    deletePrinter(printerId: string): Promise<void>;
    getAllPricingRules(): Promise<Array<PricingRule>>;
    getAllPrintJobs(): Promise<Array<PrintJob>>;
    getAllPrinters(): Promise<Array<Printer>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getPricingRuleById(ruleId: string): Promise<PricingRule | null>;
    getPrintJob(jobId: string): Promise<PrintJob | null>;
    getPrinter(printerId: string): Promise<Printer | null>;
    getTotalPrintJobs(): Promise<bigint>;
    getTotalRevenue(): Promise<bigint>;
    getUser(userId: string): Promise<User | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updatePricingRule(ruleId: string, rule: PricingRule): Promise<void>;
    updatePrinterStatus(printerId: string, status: PrinterStatus): Promise<void>;
}
import type { ColorMode as _ColorMode, ExternalBlob as _ExternalBlob, PageSize as _PageSize, PricingRule as _PricingRule, PrintJob as _PrintJob, PrintJobStatus as _PrintJobStatus, PrintSide as _PrintSide, Printer as _Printer, PrinterStatus as _PrinterStatus, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDefaultPricingRules(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDefaultPricingRules();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDefaultPricingRules();
            return result;
        }
    }
    async addPricingRule(arg0: PricingRule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPricingRule(to_candid_PricingRule_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPricingRule(to_candid_PricingRule_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculatePrice(arg0: PrintJob): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculatePrice(await to_candid_PrintJob_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculatePrice(await to_candid_PrintJob_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPrintJob(arg0: string, arg1: PrintJob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrintJob(arg0, await to_candid_PrintJob_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrintJob(arg0, await to_candid_PrintJob_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPrinter(arg0: Printer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrinter(to_candid_Printer_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrinter(to_candid_Printer_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createUser(arg0: string, arg1: User): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, to_candid_User_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, to_candid_User_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deletePricingRule(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePricingRule(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePricingRule(arg0);
            return result;
        }
    }
    async deletePrinter(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePrinter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePrinter(arg0);
            return result;
        }
    }
    async getAllPricingRules(): Promise<Array<PricingRule>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPricingRules();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPricingRules();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPrintJobs(): Promise<Array<PrintJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrintJobs();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrintJobs();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPrinters(): Promise<Array<Printer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPrinters();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPrinters();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPricingRuleById(arg0: string): Promise<PricingRule | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPricingRuleById(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPricingRuleById(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrintJob(arg0: string): Promise<PrintJob | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrintJob(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrintJob(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrinter(arg0: string): Promise<Printer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrinter(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrinter(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalPrintJobs(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalPrintJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalPrintJobs();
            return result;
        }
    }
    async getTotalRevenue(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalRevenue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalRevenue();
            return result;
        }
    }
    async getUser(arg0: string): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n65(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n65(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePricingRule(arg0: string, arg1: PricingRule): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePricingRule(arg0, to_candid_PricingRule_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePricingRule(arg0, to_candid_PricingRule_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePrinterStatus(arg0: string, arg1: PrinterStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePrinterStatus(arg0, to_candid_PrinterStatus_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePrinterStatus(arg0, to_candid_PrinterStatus_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ColorMode_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ColorMode): ColorMode {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PageSize_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageSize): PageSize {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_PricingRule_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PricingRule): PricingRule {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_PrintJobStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrintJobStatus): PrintJobStatus {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
async function from_candid_PrintJob_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrintJob): Promise<PrintJob> {
    return await from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PrintSide_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrintSide): PrintSide {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_PrinterStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PrinterStatus): PrinterStatus {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Printer_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Printer): Printer {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_User_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PricingRule]): PricingRule | null {
    return value.length === 0 ? null : from_candid_PricingRule_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PrintJob]): Promise<PrintJob | null> {
    return value.length === 0 ? null : await from_candid_PrintJob_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Printer]): Printer | null {
    return value.length === 0 ? null : from_candid_Printer_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n63(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    colorMode: _ColorMode;
    ruleId: string;
    pageSize: _PageSize;
    pricePerPage: bigint;
    printSide: _PrintSide;
}): {
    colorMode: ColorMode;
    ruleId: string;
    pageSize: PageSize;
    pricePerPage: bigint;
    printSide: PrintSide;
} {
    return {
        colorMode: from_candid_ColorMode_n34(_uploadFile, _downloadFile, value.colorMode),
        ruleId: value.ruleId,
        pageSize: from_candid_PageSize_n36(_uploadFile, _downloadFile, value.pageSize),
        pricePerPage: value.pricePerPage,
        printSide: from_candid_PrintSide_n38(_uploadFile, _downloadFile, value.printSide)
    };
}
async function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PrintJobStatus;
    colorMode: _ColorMode;
    copiesCount: bigint;
    userId: string;
    pagesPerCopyCount: bigint;
    pagesCount: bigint;
    jobId: string;
    fileBlob: _ExternalBlob;
    fileName: string;
    paperSize: _PageSize;
    fileType: [] | [string];
    sidesCount: bigint;
    colorPagesCount: bigint;
    price: bigint;
    printerId: string;
    onlyBW: boolean;
}): Promise<{
    status: PrintJobStatus;
    colorMode: ColorMode;
    copiesCount: bigint;
    userId: string;
    pagesPerCopyCount: bigint;
    pagesCount: bigint;
    jobId: string;
    fileBlob: ExternalBlob;
    fileName: string;
    paperSize: PageSize;
    fileType?: string;
    sidesCount: bigint;
    colorPagesCount: bigint;
    price: bigint;
    printerId: string;
    onlyBW: boolean;
}> {
    return {
        status: from_candid_PrintJobStatus_n43(_uploadFile, _downloadFile, value.status),
        colorMode: from_candid_ColorMode_n34(_uploadFile, _downloadFile, value.colorMode),
        copiesCount: value.copiesCount,
        userId: value.userId,
        pagesPerCopyCount: value.pagesPerCopyCount,
        pagesCount: value.pagesCount,
        jobId: value.jobId,
        fileBlob: await from_candid_ExternalBlob_n45(_uploadFile, _downloadFile, value.fileBlob),
        fileName: value.fileName,
        paperSize: from_candid_PageSize_n36(_uploadFile, _downloadFile, value.paperSize),
        fileType: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.fileType)),
        sidesCount: value.sidesCount,
        colorPagesCount: value.colorPagesCount,
        price: value.price,
        printerId: value.printerId,
        onlyBW: value.onlyBW
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PrinterStatus;
    queueCount: bigint;
    printerId: string;
}): {
    status: PrinterStatus;
    queueCount: bigint;
    printerId: string;
} {
    return {
        status: from_candid_PrinterStatus_n50(_uploadFile, _downloadFile, value.status),
        queueCount: value.queueCount,
        printerId: value.printerId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: string;
    name: string;
    role: _UserRole;
    email: string;
    phone: string;
    department: string;
}): {
    studentId: string;
    name: string;
    role: UserRole;
    email: string;
    phone: string;
    department: string;
} {
    return {
        studentId: value.studentId,
        name: value.name,
        role: from_candid_UserRole_n55(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone,
        department: value.department
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: string;
    userId: string;
    name: string;
    createdAt: bigint;
    role: _UserRole;
    email: string;
    phone: string;
    department: string;
}): {
    studentId: string;
    userId: string;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
    phone: string;
    department: string;
} {
    return {
        studentId: value.studentId,
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n55(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone,
        department: value.department
    };
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    BW: null;
} | {
    Color: null;
}): ColorMode {
    return "BW" in value ? ColorMode.BW : "Color" in value ? ColorMode.Color : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    A3: null;
} | {
    A4: null;
}): PageSize {
    return "A3" in value ? PageSize.A3 : "A4" in value ? PageSize.A4 : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Double: null;
} | {
    Single: null;
}): PrintSide {
    return "Double" in value ? PrintSide.Double : "Single" in value ? PrintSide.Single : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    uploaded: null;
} | {
    readyToPrint: null;
}): PrintJobStatus {
    return "uploaded" in value ? PrintJobStatus.uploaded : "readyToPrint" in value ? PrintJobStatus.readyToPrint : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Working: null;
} | {
    OutOfPaper: null;
} | {
    Offline: null;
}): PrinterStatus {
    return "Working" in value ? PrinterStatus.Working : "OutOfPaper" in value ? PrinterStatus.OutOfPaper : "Offline" in value ? PrinterStatus.Offline : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    student: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "student" in value ? UserRole.student : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PricingRule>): Array<PricingRule> {
    return value.map((x)=>from_candid_PricingRule_n32(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PrintJob>): Promise<Array<PrintJob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PrintJob_n41(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Printer>): Array<Printer> {
    return value.map((x)=>from_candid_Printer_n48(_uploadFile, _downloadFile, x));
}
function to_candid_ColorMode_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColorMode): _ColorMode {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PageSize_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PageSize): _PageSize {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_PricingRule_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PricingRule): _PricingRule {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_PrintJobStatus_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrintJobStatus): _PrintJobStatus {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function to_candid_PrintJob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrintJob): Promise<_PrintJob> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_PrintSide_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrintSide): _PrintSide {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_PrinterStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrinterStatus): _PrinterStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_Printer_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Printer): _Printer {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n66(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_User_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: User): _User {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: PrintJobStatus;
    colorMode: ColorMode;
    copiesCount: bigint;
    userId: string;
    pagesPerCopyCount: bigint;
    pagesCount: bigint;
    jobId: string;
    fileBlob: ExternalBlob;
    fileName: string;
    paperSize: PageSize;
    fileType?: string;
    sidesCount: bigint;
    colorPagesCount: bigint;
    price: bigint;
    printerId: string;
    onlyBW: boolean;
}): Promise<{
    status: _PrintJobStatus;
    colorMode: _ColorMode;
    copiesCount: bigint;
    userId: string;
    pagesPerCopyCount: bigint;
    pagesCount: bigint;
    jobId: string;
    fileBlob: _ExternalBlob;
    fileName: string;
    paperSize: _PageSize;
    fileType: [] | [string];
    sidesCount: bigint;
    colorPagesCount: bigint;
    price: bigint;
    printerId: string;
    onlyBW: boolean;
}> {
    return {
        status: to_candid_PrintJobStatus_n20(_uploadFile, _downloadFile, value.status),
        colorMode: to_candid_ColorMode_n10(_uploadFile, _downloadFile, value.colorMode),
        copiesCount: value.copiesCount,
        userId: value.userId,
        pagesPerCopyCount: value.pagesPerCopyCount,
        pagesCount: value.pagesCount,
        jobId: value.jobId,
        fileBlob: await to_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.fileBlob),
        fileName: value.fileName,
        paperSize: to_candid_PageSize_n12(_uploadFile, _downloadFile, value.paperSize),
        fileType: value.fileType ? candid_some(value.fileType) : candid_none(),
        sidesCount: value.sidesCount,
        colorPagesCount: value.colorPagesCount,
        price: value.price,
        printerId: value.printerId,
        onlyBW: value.onlyBW
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: PrinterStatus;
    queueCount: bigint;
    printerId: string;
}): {
    status: _PrinterStatus;
    queueCount: bigint;
    printerId: string;
} {
    return {
        status: to_candid_PrinterStatus_n25(_uploadFile, _downloadFile, value.status),
        queueCount: value.queueCount,
        printerId: value.printerId
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: string;
    userId: string;
    name: string;
    createdAt: bigint;
    role: UserRole;
    email: string;
    phone: string;
    department: string;
}): {
    studentId: string;
    userId: string;
    name: string;
    createdAt: bigint;
    role: _UserRole;
    email: string;
    phone: string;
    department: string;
} {
    return {
        studentId: value.studentId,
        userId: value.userId,
        name: value.name,
        createdAt: value.createdAt,
        role: to_candid_UserRole_n29(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone,
        department: value.department
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    studentId: string;
    name: string;
    role: UserRole;
    email: string;
    phone: string;
    department: string;
}): {
    studentId: string;
    name: string;
    role: _UserRole;
    email: string;
    phone: string;
    department: string;
} {
    return {
        studentId: value.studentId,
        name: value.name,
        role: to_candid_UserRole_n29(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone,
        department: value.department
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    colorMode: ColorMode;
    ruleId: string;
    pageSize: PageSize;
    pricePerPage: bigint;
    printSide: PrintSide;
}): {
    colorMode: _ColorMode;
    ruleId: string;
    pageSize: _PageSize;
    pricePerPage: bigint;
    printSide: _PrintSide;
} {
    return {
        colorMode: to_candid_ColorMode_n10(_uploadFile, _downloadFile, value.colorMode),
        ruleId: value.ruleId,
        pageSize: to_candid_PageSize_n12(_uploadFile, _downloadFile, value.pageSize),
        pricePerPage: value.pricePerPage,
        printSide: to_candid_PrintSide_n14(_uploadFile, _downloadFile, value.printSide)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ColorMode): {
    BW: null;
} | {
    Color: null;
} {
    return value == ColorMode.BW ? {
        BW: null
    } : value == ColorMode.Color ? {
        Color: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PageSize): {
    A3: null;
} | {
    A4: null;
} {
    return value == PageSize.A3 ? {
        A3: null
    } : value == PageSize.A4 ? {
        A4: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrintSide): {
    Double: null;
} | {
    Single: null;
} {
    return value == PrintSide.Double ? {
        Double: null
    } : value == PrintSide.Single ? {
        Single: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrintJobStatus): {
    uploaded: null;
} | {
    readyToPrint: null;
} {
    return value == PrintJobStatus.uploaded ? {
        uploaded: null
    } : value == PrintJobStatus.readyToPrint ? {
        readyToPrint: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PrinterStatus): {
    Working: null;
} | {
    OutOfPaper: null;
} | {
    Offline: null;
} {
    return value == PrinterStatus.Working ? {
        Working: null
    } : value == PrinterStatus.OutOfPaper ? {
        OutOfPaper: null
    } : value == PrinterStatus.Offline ? {
        Offline: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    student: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.student ? {
        student: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
